services:
  gestione_prenotazioni:
    build: 
      context: .
      dockerfile: ./Dockerfile
      network: host
    image: gestione_prenotazioni
    volumes:
      - ./volume/:/usr/src/app/volume/
    ports:
      - "5002:5000"
    environment:
      - PYTHONUNBUFFERED=1